version: '3.8'

services:
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    profiles:
     - "database"
     - "production"

  celery:
    image: smalltown/newsbot:0.0.3
    command: celery -A celery_app.newsBot worker --loglevel=info
    network_mode: host
    volumes:
      - "./src/.env:/usr/src/app/.env:ro"
    restart: always    
    depends_on:
      - redis
    profiles:
     - "celery"
     - "production"

  bot:
    image: smalltown/newsbot:0.0.3
    command: python bot.py
    network_mode: host
    volumes:
      - "./src/.env:/usr/src/app/.env:ro"
    restart: always
    depends_on:
      - redis
    profiles:
     - "bot"
     - "production"

  producer:
    image: smalltown/newsbot:0.0.3
    command: python producer.py
    network_mode: host
    volumes:
      - "./src/.env:/usr/src/app/.env:ro"
    restart: always
    depends_on:
      - redis
      - celery
    profiles:
     - "producer"
     - "production"

volumes:
  redis_data:
